[package]
name = "aoc2022"
version = "0.1.0"
authors = ["Denis Orlov <denorl2009@gmail.com>"]
edition = "2021"

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day02"
path = "src/day02.rs"

[dependencies]
